{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.issuer.namespace | default .Release.Namespace }}
spec:
  acme:
    email: {{ required .Values.issuer.email "issuer.email is required" }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: {{ .Values.groupName }}
          solverName: httpreq
          config:
            endpoint: {{ required .Values.issuer.endpoint "issuer.endpoint is required" }}
            {{- if .Values.issuer.headersSecretRef }}
            headerSecretRef:
              name: {{ .Values.issuer.headersSecretRef.name }}
              namespace: {{ .Values.issuer.headersSecretRef.namespace }}
            {{- end }}
{{- end }}
{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ required .Values.clusterIssuer.email "clusterIssuer.email is required" }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: acme-cluster-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: {{ .Values.groupName }}
          solverName: httpreq
          config:
            endpoint: {{ required .Values.issuer.endpoint "issuer.endpoint is required" }}
            {{- if .Values.issuer.headersSecretRef }}
            headerSecretRef:
              name: {{ .Values.issuer.headersSecretRef.name }}
              namespace: {{ .Values.issuer.headersSecretRef.namespace }}
            {{- end }}
{{- end }}
