apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "httpreq-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:auth-delegator
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "httpreq-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "httpreq-webhook.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
{{- if .Values.secrets.clusterRole.enabled }}
---
# Grant the httpreq webhook permission to read issuer header secrets at cluster scope
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:header-secrets
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
    {{- if .Values.secrets.clusterRole.names }}
    resourceNames:
      {{- range $name := .Values.secrets.clusterRole.names }}
      - {{ $name }}
      {{- end }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "httpreq-webhook.fullname" . }}:header-secrets
  labels:
    app: {{ include "httpreq-webhook.name" . }}
    chart: {{ include "httpreq-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "httpreq-webhook.fullname" . }}:header-secrets
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "httpreq-webhook.fullname" . }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- if .Values.secrets.role.enabled }}
{{- range $namespace, $names := .Values.secrets.role.namespaces }}
---
# Grant the httpreq webhook permission to read issuer header secrets at namespace scope
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "httpreq-webhook.fullname" $ }}:header-secrets
  namespace: {{ $namespace }}
  labels:
    app: {{ include "httpreq-webhook.name" $ }}
    chart: {{ include "httpreq-webhook.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
    {{- if $names }}
    resourceNames:
      {{- range $name := $names }}
      - {{ $name }}
      {{- end }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "httpreq-webhook.fullname" $ }}:header-secrets
  namespace: {{ $namespace }}
  labels:
    app: {{ include "httpreq-webhook.name" $ }}
    chart: {{ include "httpreq-webhook.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "httpreq-webhook.fullname" $ }}:header-secrets
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "httpreq-webhook.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
