groupName: acme-httpreq.saturncloud.io

issuer:
  enabled: false
  name: httpreq-issuer
  namespace:

  # replace with "https://acme-v02.api.letsencrypt.org/directory" for prod
  server: https://acme-staging-v02.api.letsencrypt.org/directory

clusterIssuer:
  enabled: false
  name: httpreq-cluster-issuer

  # replace with "https://acme-v02.api.letsencrypt.org/directory" for prod
  server: https://acme-staging-v02.api.letsencrypt.org/directory


certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/saturncloud/cert-manager-webhook-httpreq
  # Tag defaults to chart appVersion
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

logLevel: # 0

hostAliases: []
# - hostnames: ["dev.localtest.me"]
#   ip: 192.168.1.98

env: []
  # - name: ENV1
  #   value: somevalue
  # - envFrom:
  #   - secretRef:
  #       name: httpreq-secret-envs

secrets:
  # Enable httpreq to get secrets at the cluster or namespace scope
  clusterRole:
    enabled: false
    # Restrict allowed set of names
    # null/empty list implies all names are permitted
    names: []
      # - secret1
      # - secret2
  role:
    enabled: false
    # Restrict allowed set of namespaces/names
    # null/empty names list implies all names are permitted
    namespaces: {}
      # ns1:
      #   - secret1
      # ns2: []

nodeSelector: {}

tolerations: []

affinity: {}
