apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: httpreq-issuer
spec:
  acme:
    email: dev@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.saturncloud.io
          solverName: httpreq
          config:
            endpoint: http://dev.localtest.me:8889
            # headerSecretRef:
            #   name: httpreq-headers
            #   namespace: ingress
