apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app
spec:
  secretName: my-app-tls
  secretTemplate:
    labels:
      app: my-app
      role: tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - myorg.io
  dnsNames:
    - example.com
  issuerRef:
    name: httpreq-issuer
    kind: Issuer
